### ISSUE TITLE
你需要在哪里获取文件内容？

### ISSUE THREAD

**Issue by lextm** [hanfengcan/lemon#1]
https://github.com/Microsoft/vscode/issues/40852

如果你习惯讲中文，那么就在你自己的repo这边讨论吧。请用中文好好描述一下你想做什么，然后对应的代码在哪个文件的哪一行，我可以有空的时候看下哪些API是你可以使用的。

**Comment by hanfengcan** [comment]
thanks

这样子的,我在做一个串口插件.现在有一个功能,是右键的时候发送内容.

现在可以实现右键获取一行数据并通过串口发送.

另外一个功能是右键的时候获取文件的全部内容并通过串口发送,但是我没有发现有可以直接获取文件内容的API

当然可以通过`getText`来得到文件内容。不过，`new Range(start: Position, end: Position)`需要知道end的位置，也就是需要知道文件里面最后一个字符的位置。

所以我想知道有没有提供直接获取一个文件里面数据的API  
   

我的代码  

```
import { TextEditor, window } from "vscode";

export class Editor {

  private _editor: TextEditor = window.activeTextEditor;

  private static _self: Editor = null;

  public static getInstance(): Editor {
    if (Editor._self === null) {
      Editor._self = new Editor();
    }
    return Editor._self;
  }

  public sendAline() {
    let text: string = this._editor.document.lineAt(this._editor.selection.start).text;
    console.log('sendAline: ', text);
  }

  public sendAll() {
    // 这里希望获取鼠标激活的document的整个内容
    console.log('sendAll: ', this._editor);
  }

  public sendSelect() {
    let text: string = this._editor.document.getText(this._editor.selection);
    console.log('sendSelect: ', text);
  }

}
```

**Comment by lextm** [comment]
试下用`let text: string = this._editor.document.getText();`

不传参数，就应该直接获得整个文件的内容。这个其实API文档有提到，

https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument

它讲了是"the text inside the provided range **or the entire text**."

**Comment by hanfengcan** [comment]
可以了,是我没细看文档.

非常感谢.

**Comment by lextm** [comment]
祝后续开发顺利。有兴趣私聊的话，可以给我发邮件 support@lextm.com
